### ISSUE TITLE
mybatis常见错误记录 | Mr.wang's Note

### ISSUE THREAD

**Issue by lixiaw** [lixiaw/lixiaw.github.io#11]
http://www.wanglixia.top/2019/01/03/mybatis%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF%E8%AE%B0%E5%BD%95/ 

 &emsp;&emsp;Mybatis使用过程中，常见的一些问题汇总记录。  Mybatis执行SQL，查出来的比使用PL/SQL等工具查出来的记录多。问题描述：由于查询要使用到not in，因此 not in ()括号里面的东西自己使用了前端拼接传值，传值格式为’’,’’问题处理：在Mapper.xml中使用了#{}，这块涉及到#{}和${}的区别。替换成${} 就好了。

**Comment by nelucifer** [comment]
备案及统计被gitalk顶上去了

**Comment by lixiaw** [comment]
1
